# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-02 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='state',
            field=models.CharField(max_length=150),
        ),
    ]
